// GENERATED by tools/build-config.ts — do not edit by hand. Run `bun run build:config`.
//
// The built-in config the widget paints when `/v1/config/:shopKey` cannot be reached — the whole
// envelope, not just tokens, because the header needs a persona and the persona is `Voice`.
//
// Derived values are literals here BY DESIGN: derivation lives on our side of the wire
// [ENGINEERING §2.1], so the embed script must never carry `derive()` — it is a binary we cannot
// recall, and it counts against the H6 size cap. Generating them from `derive()` at build time is
// what keeps these numbers from drifting away from the real ones.
//
// `catalog` is EMPTY on purpose. The fallback is what paints when the network is gone; a bundled
// catalog is exactly the payload that belongs on the wire. A shopper still gets a greeting, their
// chips, and an honest "I cannot reach the catalogue" line rather than a blank panel.
// [ENGINEERING §2.9]

import type { ConfigResponse } from './types'

const VELDE_CONFIG: ConfigResponse = {
  tokens: {
    css: {
      '--mx-accent': '#2c3e5c',
      '--mx-text-on-accent': '#ffffff',
      '--mx-surface': '#fbfaf8',
      '--mx-surface-raised': '#e7e6e4',
      '--mx-surface-sunken': '#ffffff',
      '--mx-border': '#d3d2d0',
      '--mx-text-primary': '#000000',
      '--mx-text-muted': '#686765',
      '--mx-focus-ring': '#8c8c8c',
      '--mx-overlay-scrim': 'rgba(0, 0, 0, 0.45)',
      '--mx-space-1': '6px',
      '--mx-space-2': '12px',
      '--mx-space-3': '24px',
      '--mx-space-4': '36px',
      '--mx-space-5': '56px',
      '--mx-radius-sm': '0px',
      '--mx-radius-md': '0px',
      '--mx-radius-lg': '0px',
      '--mx-shadow-1': '0 0 0 1px rgba(0, 0, 0, 0.12)',
      '--mx-shadow-2': '0 0 0 1px rgba(0, 0, 0, 0.2)',
      '--mx-font-display': "'Inter Tight', system-ui, sans-serif",
      '--mx-font-body': "'Inter', system-ui, sans-serif",
      '--mx-text-xs': '13px',
      '--mx-text-sm': '15px',
      '--mx-text-md': '18px',
      '--mx-text-lg': '24px',
      '--mx-label-transform': 'uppercase',
      '--mx-label-tracking': '0.08em',
      '--mx-line-height': '1.55',
    },
    labelCase: 'upper-tracked',
    launcher: {
      style: 'text-anchor',
      position: 'bottom-right',
    },
    fonts: {
      display: {
        family: 'Inter Tight',
        weight: 500,
        href: 'https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500&display=swap',
      },
      body: {
        family: 'Inter',
        weight: 400,
        href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap',
      },
    },
  },
  voice: {
    name: 'VELDE',
    avatar: null,
    greeting: 'Tell me what you need it for. I will narrow it down.',
    tone: 'clipped',
  },
  strings: {
    'launcher.label': 'Help me choose',
    'panel.close': 'Close',
    'chips.legend': 'Looking for',
    'chips.drop': 'Drop {label}',
    'chips.restore': 'Put {label} back',
    'composer.placeholder': 'What is it for?',
    'composer.send': 'Send',
    clarify: 'Tell me the piece and what it has to do.',
    'recommend.lead': 'Matches:',
    'recommend.item': '{title} · {price}',
    'obstacle.text':
      'No match on all of it. {options} everything except “{blocking}”. Closest: {closest}. Tap “{blocking}” to drop it, or drop something else instead.',
    'obstacle.count.one': 'One piece fits',
    'obstacle.count.many': '{n} pieces fit',
    'no-results': 'Nothing in the range does all of that. Drop a filter and I will look again.',
    'catalog.offline':
      'I cannot reach the catalogue right now, so I cannot show you pieces. Your brief is kept. Try again in a moment.',
  },
  catalog: [],
}

const KRACHT_CONFIG: ConfigResponse = {
  tokens: {
    css: {
      '--mx-accent': '#c6f441',
      '--mx-text-on-accent': '#000000',
      '--mx-surface': '#121212',
      '--mx-surface-raised': '#202020',
      '--mx-surface-sunken': '#060606',
      '--mx-border': '#2e2e2e',
      '--mx-text-primary': '#ffffff',
      '--mx-text-muted': '#878787',
      '--mx-focus-ring': '#717171',
      '--mx-overlay-scrim': 'rgba(255, 255, 255, 0.45)',
      '--mx-space-1': '3px',
      '--mx-space-2': '7px',
      '--mx-space-3': '10px',
      '--mx-space-4': '14px',
      '--mx-space-5': '17px',
      '--mx-radius-sm': '6px',
      '--mx-radius-md': '10px',
      '--mx-radius-lg': '14px',
      '--mx-shadow-1': '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.08)',
      '--mx-shadow-2': '0 8px 24px rgba(0, 0, 0, 0.18), 0 2px 8px rgba(0, 0, 0, 0.1)',
      '--mx-font-display': "'Archivo', system-ui, sans-serif",
      '--mx-font-body': "'Inter Tight', system-ui, sans-serif",
      '--mx-text-xs': '11px',
      '--mx-text-sm': '12px',
      '--mx-text-md': '14px',
      '--mx-text-lg': '16px',
      '--mx-label-transform': 'none',
      '--mx-label-tracking': 'normal',
      '--mx-line-height': '1.3',
    },
    labelCase: 'sentence',
    launcher: {
      style: 'pill',
      position: 'bottom-right',
    },
    fonts: {
      display: {
        family: 'Archivo',
        weight: 800,
        href: 'https://fonts.googleapis.com/css2?family=Archivo:wght@700;800&display=swap',
      },
      body: {
        family: 'Inter Tight',
        weight: 500,
        href: 'https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500&display=swap',
      },
    },
  },
  voice: {
    name: 'Joep',
    avatar: {
      kind: 'illustration',
      src: '/brand/kracht/joep.svg',
    },
    greeting: "What are you training for? Tell me what you need and I'll filter as we go.",
    tone: 'warm',
  },
  strings: {
    'launcher.label': 'Ask Joep',
    'panel.close': 'Close',
    'chips.legend': 'Your filters',
    'chips.drop': 'Drop {label}',
    'chips.restore': 'Put {label} back',
    'composer.placeholder': 'Tell me what you need',
    'composer.send': 'Send',
    clarify: 'Give me something to work with — a goal, an ingredient, a budget.',
    'recommend.lead': "Here's what fits:",
    'recommend.item': '{title} · {price}',
    'obstacle.text':
      "Nothing clears all of it. {options} everything except “{blocking}” — the closest is {closest}. Tap “{blocking}” to drop it and I'll show you those, or keep it and drop something else.",
    'obstacle.count.one': 'One option fits',
    'obstacle.count.many': '{n} options fit',
    'no-results': "Nothing in the range does all that. Drop one filter and I'll look again.",
    'catalog.offline':
      "I can't reach the catalogue right now, so I can't check what's in stock. Your filters are saved — try me again in a minute.",
  },
  catalog: [],
}

/** Keyed by `data-shop`. An unknown key has no brand, so the loader fails loudly instead. */
export const FALLBACK: Record<string, ConfigResponse> = {
  velde: VELDE_CONFIG,
  kracht: KRACHT_CONFIG,
}

/**
 * The custom properties the shadow stylesheet actually references. The runtime guard checks a
 * fetched payload against this list, so "the API dropped a variable" is caught at the boundary
 * rather than as a blank panel.
 */
export const CSS_VAR_NAMES: string[] = Object.keys(VELDE_CONFIG.tokens.css)
