import { describe, expect, test } from 'bun:test'
import { loadCatalog } from './brain/catalog'
import { createBrain, step } from './brain/fsm'
import { chipsFrom } from './brain/parse'
import type { CacheStore } from './config'
import { reply } from './converse'
import { configUrl, isConfigResponse, readCache, str, writeCache } from './config'
import { cornerCss } from './css'
import { FALLBACK } from './fallback'
import type { Block, Product } from './types'

/**
 * The pure half of the shell. DOM behaviour — focus trap, 375px layout, shadow isolation — is
 * Playwright's job in T12; asserting it here against a fake DOM would prove nothing about a
 * browser. [ENGINEERING §3.8]
 *
 * Imports `./config` and `./css` directly, never `./index`: the barrel pulls in `widget.ts`, whose
 * `extends HTMLElement` cannot even be evaluated outside a browser.
 */

const velde = FALLBACK.velde
if (velde === undefined) throw new Error('fixture missing: FALLBACK.velde')
const kracht = FALLBACK.kracht
if (kracht === undefined) throw new Error('fixture missing: FALLBACK.kracht')

function fakeStore(): CacheStore & { data: Map<string, string> } {
  const data = new Map<string, string>()
  return {
    data,
    getItem: (key) => data.get(key) ?? null,
    setItem: (key, value) => {
      data.set(key, value)
    },
  }
}

describe('config URL', () => {
  test('resolves against the script origin, not the storefront', () => {
    expect(configUrl('https://maximal.releashed.io/v1/agent.js', 'velde')).toBe(
      'https://maximal.releashed.io/v1/config/velde',
    )
  })

  test('ignores the script path and query, keeps the port', () => {
    expect(configUrl('http://localhost:4000/static/embed/agent.js?v=3', 'kracht')).toBe(
      'http://localhost:4000/v1/config/kracht',
    )
  })

  test('escapes a shop key rather than letting it walk the path', () => {
    expect(configUrl('https://maximal.releashed.io/v1/agent.js', '../admin')).toBe(
      'https://maximal.releashed.io/v1/config/..%2Fadmin',
    )
  })
})

describe('localStorage cache', () => {
  test('round-trips a config', () => {
    const store = fakeStore()
    writeCache(store, 'velde', velde)
    expect(store.data.size).toBe(1)
    expect(readCache(store, 'velde')).toEqual(velde)
  })

  test('a miss, unparseable JSON and a stale shape all read as no cache', () => {
    const store = fakeStore()
    expect(readCache(store, 'velde')).toBe(null)
    store.data.set('mx-config-velde', '{not json')
    expect(readCache(store, 'velde')).toBe(null)
    store.data.set('mx-config-velde', JSON.stringify({ tokens: {}, voice: {} }))
    expect(readCache(store, 'velde')).toBe(null)
  })

  test('a throwing storage (private mode, quota) is survivable', () => {
    const angry: CacheStore = {
      getItem: () => {
        throw new Error('SecurityError')
      },
      setItem: () => {
        throw new Error('QuotaExceededError')
      },
    }
    expect(readCache(angry, 'velde')).toBe(null)
    expect(() => writeCache(angry, 'velde', velde)).not.toThrow()
  })
})

describe('config guard', () => {
  test('accepts every brand bundled into FALLBACK', () => {
    // Named rather than counted. `FALLBACK` is generated by `tools/build-config.ts` from its SHOPS
    // registry minus `default`, so this list IS the bundle's contents: a brand silently dropping
    // out fails here, and adding one (T11 added `helder`) is a deliberate one-line edit rather
    // than a count that quietly tracks whatever happens to be there.
    expect(Object.keys(FALLBACK).sort()).toEqual(['helder', 'kracht', 'velde'])
    for (const brand of Object.values(FALLBACK)) expect(isConfigResponse(brand)).toBe(true)
  })

  test('rejects the shapes a broken endpoint actually returns', () => {
    const cases: unknown[] = [
      null,
      undefined,
      'not an object',
      {},
      { tokens: velde.tokens, voice: velde.voice, strings: {} },
      { ...velde, catalog: [{ id: 'p1' }] },
      { ...velde, strings: { 'panel.close': 7 } },
      { ...velde, voice: { ...velde.voice, avatar: { kind: 'photo', src: '/a.png' } } },
    ]
    expect(cases.length).toBeGreaterThan(0)
    for (const shape of cases) expect(isConfigResponse(shape)).toBe(false)
  })

  test('rejects a payload that dropped a single custom property', () => {
    const css: Record<string, string> = { ...velde.tokens.css }
    delete css['--mx-focus-ring']
    expect(isConfigResponse({ ...velde, tokens: { ...velde.tokens, css } })).toBe(false)
  })
})

describe('launcher corner', () => {
  test('every corner resolves to its two edges', () => {
    const gap = 'var(--mx-space-4)'
    expect(cornerCss('bottom-right')).toBe(`bottom: ${gap}; right: ${gap};`)
    expect(cornerCss('bottom-left')).toBe(`bottom: ${gap}; left: ${gap};`)
    expect(cornerCss('top-right')).toBe(`top: ${gap}; right: ${gap};`)
    expect(cornerCss('top-left')).toBe(`top: ${gap}; left: ${gap};`)
  })
})

describe('merchant copy', () => {
  test('a missing key renders as the key, never as "undefined"', () => {
    expect(str(velde.strings, 'composer.send')).toBe('Send')
    expect(str(velde.strings, 'nope.missing')).toBe('nope.missing')
  })
})

/**
 * The graded turn, end to end without a DOM: the shopper's sentence in, the merchant's own words
 * out, with the blocking constraint and its cost computed from the REAL catalog. `reply` is the
 * only piece between the brain and `push()`, so this fails if the template stops interpolating,
 * if the obstacle stops naming a number, or if dropping the chip stops rescuing anything.
 */
function said(blocks: Block[]): string[] {
  return blocks.flatMap((block) => (block.kind === 'text' ? [block.text] : []))
}

/**
 * The product titles a turn recommended. Before T5 these arrived as `text` blocks, because
 * `converse.ts` flattened every card into a sentence; they are `product-card` blocks now and the
 * renderer draws title and price itself. Same invariant, read off the block that actually carries
 * it — which is also stronger, since it no longer passes just because a title appeared in prose.
 */
function recommended(blocks: Block[]): string[] {
  return blocks.flatMap((block) => (block.kind === 'product-card' ? [block.product.title] : []))
}

/**
 * The reading `apps/platform/chat.ts` returns for each brand's verbatim PRINCIPLES §8 opening
 * message — the sentences these two consts used to be. The merchant's own `strings` go in as the
 * second argument because that is what the real path passes, and this file asserts on chip LABELS
 * reaching the obstacle sentence. (`chip-price`'s label is generated by `chipsFrom` itself.)
 */
const KRACHT_OPENING = chipsFrom(
  { tags: ['protein-shake', 'no-sweeteners', 'lactose-free'], maxPrice: 30 },
  kracht.strings,
)
const VELDE_OPENING = chipsFrom(
  { tags: ['jacket', 'office', 'bike', 'black', 'matte'], maxPrice: 250 },
  velde.strings,
)

describe('the obstacle sentence', () => {
  test('names the blocking constraint, quantifies it, and resolves when the chip is dropped', async () => {
    const catalog = await loadCatalog('packages/agent/src/brain/catalog.kracht.json')
    expect(catalog.length).toBeGreaterThan(0)

    const opening = step(createBrain(catalog), {
      type: 'message',
      chips: KRACHT_OPENING,
      dropped: [],
    })
    const sentence = said(reply(opening.blocks, opening.state, kracht.strings)).join(' ')
    expect(sentence.length).toBeGreaterThan(0)
    // The blocking chip's own label, and the real price of the nearest product — neither is a
    // literal anywhere in the payload; both are interpolated into the template.
    expect(sentence).toContain('under €30')
    // Derive the expected number from the catalog rather than pinning a literal. The first
    // version of this test hardcoded '€49'; a catalog change made the sentence correctly say
    // €32.95 and the test failed for being right. The invariant is "the cheapest product that
    // clears every constraint except price is the number quoted" — that survives merchandising.
    const cheapestNearMiss = catalog
      .filter((p) => p.tags.includes('no-sweeteners') && p.tags.includes('lactose-free'))
      .reduce((low, p) => (p.price < low ? p.price : low), Number.POSITIVE_INFINITY)
    expect(cheapestNearMiss).toBeLessThan(Number.POSITIVE_INFINITY)
    expect(sentence).toContain(String(cheapestNearMiss))
    expect(sentence).not.toContain('{')

    const dropped = step(opening.state, { type: 'drop-chip', id: 'chip-price' })
    const rescued = reply(dropped.blocks, dropped.state, kracht.strings)
    expect(said(rescued)[0]).toBe(kracht.strings['recommend.lead'])
    expect(recommended(rescued).length).toBeGreaterThan(0)
    expect(recommended(rescued).some((title) => title.includes('Isolate'))).toBe(true)

    const restored = step(dropped.state, { type: 'restore-chip', id: 'chip-price' })
    expect(said(reply(restored.blocks, restored.state, kracht.strings)).join(' ')).toContain(
      'under €30',
    )
  })

  test('the brand that resolves happily says so, in its own voice', async () => {
    const catalog = await loadCatalog('packages/agent/src/brain/catalog.velde.json')
    const opening = step(createBrain(catalog), {
      type: 'message',
      chips: VELDE_OPENING,
      dropped: [],
    })
    const blocks = reply(opening.blocks, opening.state, velde.strings)
    const lines = said(blocks)
    expect(lines[0]).toBe('Matches:')
    // The price now lives on the card, not in prose, so the assertion reads the block's own
    // product. Derived from the catalog rather than pinned, for the reason stated above.
    const cheapest = Math.min(
      ...blocks.flatMap((b) => (b.kind === 'product-card' ? [b.product.price] : [])),
    )
    expect(cheapest).toBe(245)
    expect(lines.join(' ')).not.toContain('except')
  })

  test('a fallback with no catalog answers honestly instead of silently', () => {
    const opening = step(createBrain([]), { type: 'message', chips: KRACHT_OPENING, dropped: [] })
    const lines = said(reply(opening.blocks, opening.state, kracht.strings))
    expect(lines.length).toBe(1)
    expect(lines[0]).toBe(kracht.strings['catalog.offline'])
  })
})

/**
 * The recommend cap [fsm.ts RESULT_CAP] and its disclosure [converse.ts `recommendMoreText`], end
 * to end: a goal-shaped brief can legitimately match most of a catalog, and this is the pair of
 * moves that keeps the panel from becoming a scroll wall — cap the cards, then say so instead of
 * truncating silently. A synthetic catalog rather than a real one: the assertion below is on exact
 * prices, and pinning that to `catalog.kracht.json` would make the test fragile to merchandising
 * the same way the obstacle-sentence tests above deliberately avoid (see their own comment).
 */
describe('the recommend cap', () => {
  const bulkProduct = (n: number): Product => ({
    id: `bulk-${n}`,
    title: `Bulk ${n}`,
    url: '',
    image: null,
    price: n * 10,
    currency: 'EUR',
    inStock: true,
    specs: [],
    tags: ['creatine'],
  })
  // One tag, nine matches — comfortably above RESULT_CAP(6) so both a "no cap" regression and a
  // "disclosure never fires" regression would show up.
  const bulkCatalog = Array.from({ length: 9 }, (_, i) => bulkProduct(i + 1))
  const bulkChips = chipsFrom({ tags: ['creatine'] }, kracht.strings)

  test('more than 6 matches are capped at 6, cheapest first, with a trailing disclosure', () => {
    const opening = step(createBrain(bulkCatalog), {
      type: 'message',
      chips: bulkChips,
      dropped: [],
    })
    const blocks = reply(opening.blocks, opening.state, kracht.strings)

    expect(recommended(blocks).length).toBe(6)
    // Cheapest first survives the cut: the six lowest prices, not just any six.
    expect(blocks.flatMap((b) => (b.kind === 'product-card' ? [b.product.price] : []))).toEqual([
      10, 20, 30, 40, 50, 60,
    ])

    // Exactly two lines of prose: the lead-in, then the disclosure — trailing AFTER every card,
    // not leading before them, and naming both numbers.
    const lines = said(blocks)
    expect(lines.length).toBe(2)
    expect(lines[0]).toBe(kracht.strings['recommend.lead'])
    const disclosure = lines[1]
    expect(disclosure).toContain('6')
    expect(disclosure).toContain('9')
    // Never the raw key: a shopper must never read the literal string "recommend.more".
    expect(disclosure).not.toBe('recommend.more')
  })

  test('a config minted before recommend.more existed still discloses, in the built-in sentence', () => {
    // ~150 runtime-minted shop-*.json configs predate this key [converse.ts BUILT_IN_RECOMMEND_MORE].
    const legacyStrings = Object.fromEntries(
      Object.entries(kracht.strings).filter(([key]) => key !== 'recommend.more'),
    )
    const opening = step(createBrain(bulkCatalog), {
      type: 'message',
      chips: bulkChips,
      dropped: [],
    })
    const disclosure = said(reply(opening.blocks, opening.state, legacyStrings)).at(-1)
    expect(disclosure).toBeDefined()
    expect(disclosure).toContain('6')
    expect(disclosure).toContain('9')
    expect(disclosure).not.toBe('recommend.more')
  })

  test('6 or fewer matches need no disclosure at all', () => {
    const smallCatalog = bulkCatalog.slice(0, 6)
    const opening = step(createBrain(smallCatalog), {
      type: 'message',
      chips: bulkChips,
      dropped: [],
    })
    const blocks = reply(opening.blocks, opening.state, kracht.strings)
    expect(recommended(blocks).length).toBe(6)
    // The lead-in is the only text: nothing hidden, nothing to disclose.
    const lines = said(blocks)
    expect(lines.length).toBe(1)
    expect(lines[0]).toBe(kracht.strings['recommend.lead'])
  })
})
